//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetsWebLicencePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projet()
        {
            this.tache = new HashSet<tache>();
            this.personne = new HashSet<personne>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public string url { get; set; }
        public string mail { get; set; }
        public string description { get; set; }
        public string logo { get; set; }
        public Nullable<int> Id_entreprise { get; set; }
        public Nullable<int> Id_promo { get; set; }
    
        public virtual entreprise entreprise { get; set; }
        public virtual promo promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tache> tache { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personne> personne { get; set; }
    }
}
