//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetsWebLicencePro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tache
    {
        public int Id { get; set; }
        public string description { get; set; }
        public Nullable<int> Id_projet { get; set; }
        public Nullable<int> valeur { get; set; }
        public Nullable<System.DateTime> startedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public Nullable<int> Id_categorie { get; set; }
    
        public virtual categorie categorie { get; set; }
        public virtual projet projet { get; set; }
    }
}
